AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an S3 Bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-unique-s3-bucket-name-12345   # Must be globally unique or omit to let AWS auto-generate
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: MyS3Bucket
        - Key: Environment
          Value: Dev

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
